"""
Django settings for travel_itinerary_backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5($d0xrq@v%n1q&m5n37$)e6htw)#4+8t^iipe)_5hdw@gm)p9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'travel_itinerary',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'djangosaml2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travel_itinerary_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travel_itinerary_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'TravelItinerary', #Name of the database created for this project
        'HOST': 'REFL-RLP409\\SQLSERVEREXP22',
        'PORT': '',
         'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes', 
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True



AUTHENTICATION_BACKENDS = [
    'djangosaml2.backends.Saml2Backend',
    'django.contrib.auth.backends.ModelBackend',
]


# SAML Service Provider configuration
SAML_CONFIG = {
    'xmlsec_binary': r'C:\Program Files\XMLSec\bin\xmllint.exe',  # adjust for your xmlsec binary
    'entityid': 'https://wti.onreflections.com',
    'service': {
        'sp': {
            'name': 'XTAM SP',
            'endpoints': {
                # Azure will POST to this path (it may include query string)
                'assertion_consumer_service': [
                    ('https://wti.onreflections.com/cas/login', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'),
                ],
                'single_logout_service': [
                    ('https://wti.onreflections.com/saml2/ls/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'),
                ],
            },
            'allow_unsolicited': True,
            'authn_requests_signed': False,
            'want_assertions_signed': True,
            'name_id_format': 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
        },
    },
    # IdP metadata: prefer the Federation Metadata XML URL you downloaded from Azure
    'metadata': {
        'local': [r'd:\Travel Itinerary\azure_federationmetadata.xml'],  # or 'remote': [(url, {})]
    },
    # attribute mapping from SAML assertions -> Django user fields
    'attribute_map': {
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress': ('email',),
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname': ('first_name',),
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname': ('last_name',),
    },
}
# # ...existing code...
# LOGIN_URL = 'https://login.microsoftonline.com/b0b120fd-1701-4d59-9e7d-9cdfeed9fcc0/saml2'
# LOGIN_REDIRECT_URL = 'https://login.microsoftonline.com/b0b120fd-1701-4d59-9e7d-9cdfeed9fcc0/saml2'
# ALLOWED_HOSTS += ['wti.onreflections.com']